version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: finance-dashboard-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: finance-dashboard
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - finance-network

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: finance-dashboard-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - finance-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  finance-network:
    driver: bridge
